#!/bin/bash
# $Id$
# License: do what you want to.
# Originally written by Max Chernoff, 31jul2024.
# Extract urls from a pdf, or as given, and check them. Assume GNU grep
# and bash (for pipefail).

referer_domain=freefriends.org # sometimes helps to not be blocked
                               # don't use tug for fear of blacklisting
# update from time to time:
agent="Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"

exit_status=0
set -o pipefail

# take list of urls on stdin and wget each.
ckurls () {
  wget -i- -nv --no-check-cert --wait=1 --timeout=4 --tries=1 --spider \
       --user-agent="$agent"
       --referer=https://$referer_domain \
       2>&1 \
  | tee /dev/stderr # so we get output as it goes along
  test $exit_status -eq 0 || exit_status=$?
}

# doesn't actually do the substitutions.
#  | sed --unbuffered -e 's/^.* URL: //' -e 's/:$//' \

for f in "$@"; do
  if test "x$f" = x--file; then
    shift
    # take urls from file
    if test -s "$1"; then
      file=$1
      shift
      cat "$file" || exit 1
    else
      echo "$0: argument to --file has no urls: $1" >&2
      exit 1
    fi

  # url given on command line
  elif echo "$f" | grep '^http' >/dev/null; then
    echo "$f"

  else # assume it's a pdf
    # We exclude adobe.com since it does not respond to wget requests
    # (but maybe it will with user-agent, etc., so try agan)
    # 
    # Exclude "." which happens with spelatex (tb142).
    # 
    #With wget v1.xx (which is what the tug.org server is using):
    qpdf --qdf "$f" - \
    | grep -aoP '(?<=/URI \()[^)]*(?=\))' \
    | grep -avF example.org \
    | grep -avF xadobe.com \
    | grep -av  '^\.' \
    | sort -u
  fi
done | tee /tmp/ckurl.in \
| ckurls \
>/tmp/ckurl

exit $exit_status

# output looks like:
#  2024-08-03 08:55:39 URL: https://github.com/borisveytsman/bookshelf 200 OK
# or on error:
#  https://www.perplexity.ai/:
#  Remote file does not exist -- broken link!!!
# which is why we remove trailing colons in the last sed.

#With wget v2.xx (which is what I have installed locally), try:
#   qpdf --qdf /path/to/file.pdf - | grep -aoP '(?<=/URI \()[^)]*(?=\))' | wget --spider -i- | grep ^HTTP

# Basic idea for checking urls in html:
# @links = $html =~ m/<a[^>]+href\s*=\s*["']?([^"'> ]+)/ig;
