#!/bin/sh
# $Id$
# Run context --luatex for TUGboat. Public domain.
# Run from PATH, i.e., current TL.
# To run from a ConTeXt tree, see lmtxtub and lmtx.

exec context --luatex --batchmode "$@"
# --noconsole omits logging to terminal, better to redirect.
