#!/bin/sh
# $Id: ps2pdf-tub 296 2020-09-14 20:53:13Z karl $
# Public domain.
# 
# Excise the "PDFCROP" version line, preserve exit status.

for f in "$@"; do
  out=${TMPDIR-/tmp}/pdfcroptub.$$
  pdfcrop "$f" >$out
  status=$?
  grep -v '^PDFCROP 1\.' $out
  if test $status != 0; then
    echo "$0: failed on: $f" >&2
    cat $out
    exit $status
  fi
done

rm -f $out
exit 0
