#!/bin/sh
# $Id$
# Public domain.
# 
# Convert input $1 to output $2, converting color to cmyk.
# https://stackoverflow.com/questions/48936435/
# and adding ColorConversionStrategyForImages.
# 
# We output PDF1.3 since that is what Cadmus uses for printing,
# according to their proof pdfs. Therefore we should generate the same
# version to avoid surprises, such as the f-ligatures disappearing in
# tb145sojka-doctor-mittelbach.  WriteXRefStm and WriteObjStms avoid
# compressed streams for strict PDF/A compliance/bug avoidance.
# 
# See ps2pdf-tub for details about other options.

if test $# -ne 2; then
  echo "Usage: $0 INFILE OUTFILE" >&2
  exit 1
fi

: ${gs=gs}
exec $gs -q -dNOPAUSE -dBATCH \
  -sDEVICE=pdfwrite \
  -sOutputFile="$2" \
  -r1200 \
  -dAutoRotatePages=/None \
  -dCompressFonts=true \
  -dDetectDuplicateImages \
  -dEmbedAllFonts \
  -dPDFSETTINGS=/prepress \
  -dPrinted=false \
  \
  -sColorConversionStrategy=CMYK \
  -sColorConversionStrategyForImages=CMYK \
  -dProcessColorModel=/DeviceCMYK \
  \
  -dCompatibilityLevel=1.3 \
  -dWriteXRefStm=false \
  -dWriteObjStms=false \
  -f "$1"

# For downsampling images to 300dpi since that's all LSI accepts,
# but so far we're not bothering.
#gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 \
#   -dNOPAUSE -dQUIET -dBATCH \
#   -dDownsampleColorImages=true -dColorImageResolution=300 -dColorImageDownsampleThreshold=1.0 \
#   -dDownsampleGrayImages=true -dGrayImageResolution=300 -dGrayImageDownsampleThreshold=1.0 \
#   -dDownsampleMonoImages=true -dMonoImageResolution=300 -dMonoImageDownsampleThreshold=1.0 \
#   -sOutputFile=output.pdf input.pdf

# -dDownsample[Color/Gray/Mono]Images=true
# -d[Color/Gray/Mono]ImageResolution=300
# -d[Color/Gray/Mono]ImageDownsampleThreshold=1.0: Forces Ghostscript
# to compress any image exceeding 300 DPI. Setting this to 1.0 ensures
# no high-resolution images bypass the downsampling filter. 
