#!/bin/sh
# $Id$
# Public domain.
# 
# ps2pdf (or pdf2pdf), but always embedding fonts, and optionally with
# Jacko's distillation parameters to prevent gs from reducing resolution
# of embedded bitmaps, and allow just one filename arg, meaning overwrite.

: ${gs=gs}
: ${zdistill=""} #-f ../zdistill.rip"}
: ${zres=""}     #-r150 to reduce image resolutions, or options below.

if test $# -eq 1; then
  set - "$1" "$1.tmppdf"
elif test $# -ne 2; then
  echo "Usage: $0 IN[OUT]FILE [OUTFILE]" >&2
  exit 1
fi

# -r1200 is to avoid rendering on a tiny canvas, which can trip
#   heuristics of complicated fonts, as (relating to a Hans font) in:
#   https://bugs.ghostscript.com/show_bug.cgi?id=701753 
# -dAutoRotatePages since we do not want pages randomly rotated.
# -dCompressFonts seems not to hurt, and can save notable space.
# -dDetectDuplicateImages similarly.
# -dEmbedAllFonts usually but doesn't always work to embed fonts,
#   except that if downscaling images with zres, have to override.
# -dPDFSETTINGS=/prepress needed for embedding with
#   45-2/watters-litigator/doc.pdf (tb140)
# -dPrinted=false is to preserve internal links within the pdf,
#   notably for the cover/cover3 in our tb*complete.pdf:
#   https://tex.stackexchange.com/questions/456896
# -dColorImageResolution and -dGrayImageResolution because the default
#   is 300 and we might as well do more for TUGboat. The default
#   MonoImageResolution is already 1200. Per
#     https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#distiller-parameters
#   and this message from Bruno Voisin:
#     https://tug.org/pipermail/tex-live/2025-March/051333.html

#set -x
$gs -q -dNOPAUSE -dBATCH \
  -sDEVICE=pdfwrite \
  -sOutputFile="$2" \
  -r1200 \
  -dAutoRotatePages=/None \
  -dCompressFonts=true \
  -dDetectDuplicateImages \
  -dEmbedAllFonts \
  -dPDFSETTINGS=/prepress \
  -dPrinted=false \
  -dColorImageResolution=1200 \
  -dGrayImageResolution=1200 \
  $zdistill $zres \
  -f "$1" 

#   but seems to be no longer necessary.
# old: -dPDFX=true failure with annotations in gs 9.14 (tb109reviews-xie), 
# old: -c .setpdfwrite used to be necessary, but no longer is?
# old: quit.ps disappeared in gs 9.22.

if test x"$2" = "x$1.tmppdf"; then
  cp "$1" ${TMPDIR-/tmp}/ps2pdf-`basename "$1"`
  mv "$2" "$1"
fi

# Re image compression, the default seems good enough for us, since we
# usually do want some sort of compression. explanation of many options,
# including the way to see all default settings for pdfwrite:
# https://superuser.com/questions/360216/use-ghostscript-but-tell-it-to-not-reprocess-images
# namely:
# gs -sDEVICE=pdfwrite -o /dev/null \
#    -c "currentpagedevice { exch ==only ( ) print == } forall"
#
# but if we ever did want to leave images alone, maybe (from that same page):
# -dColorConversionStrategy=/LeaveColorUnchanged \
# -dDownsampleColorImages=false \
# -dDownsampleGrayImages=false \
# -dDownsampleMonoImages=false \
# -dAutoFilterColorImages=false \
# -dAutoFilterGrayImages=false \
# -dColorImageFilter=/FlateEncode \
# -dGrayImageFilter=/FlateEncode \
# -dMonoImageFilter=/CCITTFaxEncode

# other random options sometimes of interest:
# -dDEVICEWIDTHPOINTS=679 -dDEVICEHEIGHTPOINTS=1598
# -sPAPERSIZE=a4

# See also https://github.com/pts/pdfsizeopt and sam2p, maybe.
