#!/bin/sh
# Copyright 2009-2018 TeX Users Group.
# $Id$
# You may freely use, modify and/or distribute this file.
# 
# ps2pdf (or pdf2pdf), but always embedding fonts, and optionally with
# Jacko's distillation parameters to prevent gs from reducing resolution
# of embedded bitmaps, and allow just one filename arg, meaning overwrite.

: ${gs=gs}
: ${zdistill=""} #-f ../zdistill.rip"}
: ${zres=""}     #-r150 to reduce image resolutions, or options below.

if test $# -eq 1; then
  set - "$1" "$1.tmppdf"
fi

# -dDEVICEWIDTHPOINTS=679 -dDEVICEHEIGHTPOINTS=1598
# -sPAPERSIZE=a4

# with gs 9.14 (tb109reviews-xie), -dPDFX=true fails with annotations,
# -dEmbedAllFonts doesn't, but -dPDFSETTINGS=/prepress does the job so
# far -- except that when downscaling images with zres, have to override.
# 
# -dCompressFonts seems not to hurt, and can save notable space.
#set -x
$gs \
   -q -dNOPAUSE -dBATCH \
   -sDEVICE=pdfwrite \
   -dEmbedAllFonts -dPDFSETTINGS=/prepress -dAutoRotatePages=/None \
   -dCompressFonts=true \
   -dDetectDuplicateImages \
   $zdistill $zres \
   -sOutputFile="$2" \
   -f "$1" 

# -c .setpdfwrite used to be necessary, but no longer is?
# quit.ps disappeared in gs 9.22.

if test x"$2" = "x$1.tmppdf"; then
  cp "$1" ${TMPDIR-/tmp}/ps2pdf-`basename "$1"`
  mv "$2" "$1"
fi

# the default seems good enough for us, since we usually do want some
# sort of compression. explanation of many options, including the way to
# get all default settings for pdfwrite:
# https://superuser.com/questions/360216/use-ghostscript-but-tell-it-to-not-reprocess-images
# namely:
# gs -sDEVICE=pdfwrite -o /dev/null \
#    -c "currentpagedevice { exch ==only ( ) print == } forall"
#
# but if we ever did want to leave images alone, maybe (from that same page):
# -dColorConversionStrategy=/LeaveColorUnchanged \
# -dDownsampleColorImages=false \
# -dDownsampleGrayImages=false \
# -dDownsampleMonoImages=false \
# -dAutoFilterColorImages=false \
# -dAutoFilterGrayImages=false \
# -dColorImageFilter=/FlateEncode \
# -dGrayImageFilter=/FlateEncode \
# -dMonoImageFilter=/CCITTFaxEncode

# See also https://github.com/pts/pdfsizeopt and sam2p, maybe.
