#!/bin/sh
# $Id$
# Public domain.
# 
# Convert input $1 to output $2, converting color to grayscale,
# including text.
# 
# We could convert text to black with -dBlackText; see
# https://ghostscript.readthedocs.io/en/gs10.05.1/Use.html
# (or current version). But it seems when text is colored in TUGboat,
# it's often an intentional example, so better to be grayscaled than black.
# 
# Also, we convert to PDF 1.3 because almost always the purpose of
# grayscaling is for printing, and Cadmus' process uses 1.3.
# See ps2pdf-cmyk-tub for more details on that, and
# see ps2pdf-tub for comments on other settings.
# 
# For grayscaling, see also (some may no longer work):
# http://handyfloss.net/2008.09/making-a-pdf-grayscale-with-ghostscript/--isilanes 
# https://stackoverflow.com/questions/20128656/how-to-convert-a-pdf-to-grayscale-from-command-line-avoiding-to-be-rasterized
# https://superuser.com/questions/200378/converting-a-pdf-to-black-white-with-ghostscript
# https://stackoverflow.com/a/23553427
# https://unix.stackexchange.com/questions/93959/how-to-convert-a-color-pdf-to-black-white
# https://ghostscript.readthedocs.io/en/latest/Use.html

if test $# -ne 2; then
  echo "Usage: $0 INFILE OUTFILE" >&2
  exit 1
fi

: ${gs=gs}
exec $gs -q -dNOPAUSE -dBATCH \
  -sDEVICE=pdfwrite \
  -sOutputFile="$2" \
  -r1200 \
  -dAutoRotatePages=/None \
  -dCompressFonts=true \
  -dDetectDuplicateImages \
  -dEmbedAllFonts \
  -dPrinted=false \
  \
  -sColorConversionStrategy=Gray \
  -dProcessColorModel=/DeviceGray \
  \
  -dCompatibilityLevel=1.3 \
  -dWriteXRefStm=false \
  -dWriteObjStms=false \
  \
  -f "$1"
