#!/bin/sh
# $Id$
# Public domain.
# 
# Convert input $1 to output $2, converting color to grayscale.
# 
# See also:
# http://handyfloss.net/2008.09/making-a-pdf-grayscale-with-ghostscript/
# --isilanes 
# https://stackoverflow.com/questions/20128656/how-to-convert-a-pdf-to-grayscale-from-command-line-avoiding-to-be-rasterized
# https://superuser.com/questions/200378/converting-a-pdf-to-black-white-with-ghostscript
# https://stackoverflow.com/a/23553427
# https://unix.stackexchange.com/questions/93959/how-to-convert-a-color-pdf-to-black-white
# https://ghostscript.com/doc/9.16/Use.htm
# 
# See ps2pdf-tub for comments on other settings.

if test $# -ne 2; then
  echo "Usage: $0 INFILE OUTFILE" >&2
  exit 1
fi

: ${gs=gs}
exec $gs -q -dNOPAUSE -dBATCH \
  -sDEVICE=pdfwrite \
  -sOutputFile="$2" \
  -r1200 \
  -dAutoRotatePages=/None \
  -dCompressFonts=true \
  -dDetectDuplicateImages \
  -dEmbedAllFonts \
  -dPrinted=false \
  \
  -sColorConversionStrategy=Gray \
  -dProcessColorModel=/DeviceGray \
  -f "$1"
