#!/bin/sh
# $Id$
# This is used to create a plain text version of the table of contents
# to send to tex-eds@tug.org after an issue is published.
# (See /home/tubprod/README.) In short:
#   save contentsVV-N.html as text, then run this, check for nonascii
#   characters (done below), edit result, mail tex-eds.

sed '1,/Complete issue/d' "$@" \
| deutf \
| tee /tmp/lat \
| expand \
| sed \
  -e 's,/,,g' \
  -e 's/<.*>//g' \
  -e 's/^\*\(.*\)\*/-- \1/' \
  -e 's/ *\\Dash */ -- /g' \
  -e 's/… */.../g' \
  -e 's/“/`/g' \
  -e "s/”/'/g" \
  -e 's/–/-/g' \
  -e 's/—/--/g' \
  -e "s/é/\\'e/g" \
  -e 's/ö/\\"o/g' \
  -e 's/âŸ¨/</g' \
  -e 's/âŸ©/>/g' \
  -e 's/    */  /g' \
  -e 's/^\([\a-z`]\)/    \1/' \
  -e 's/^    //' \
  -e 's/  *,/,/g' \
| grep -v '^[ )]*$' \
| sed -z -e 's/ *\n,/,/g' \
| sed -z -e 's/\n *\([0-9c]\)/ \1/g' \
| sed -e 's/  *,/,/g' -e 's/^ *$//' -e 's/  *$//' -e '/^$/d' \
| tee /tmp/tubtoc \
| perl -pg -e 's,<.*?>,,sg' \
| sed -z -e 's/\n--/\n\n--/g' \
| sed -e 's/^\([a-z]\)/    \1/' \
| sed -e 's/(doi *)*//g' \
      -e 's/(orcid *)*//g' \
| grep -v '^ \+$' \
| sed '/^TUG home page/,$d'

# -g to perl says to read the whole file as one string;
# then the non-greedy .*? can remove across newlines,
# since the browser helpfully breaks urls at dashes.
# none of this is quite right yet ...

set -x
nonascii-tub /tmp/lat
nonascii-tub /tmp/tubtoc
