#!/bin/sh
# $Id$
# Copy .bbl files for Crossref. Public domain.
# 
# As a first step toward preparing the <citation_list> elements for the
# Crossref upload (see ltx2crossrefxml, crossref/README, etc.), we copy
# any bbl and abstract files for a given issue $1 to the temporary
# holding directory $2.
# 
# We're going to assume there are no spaces in filenames, etc.,
# cp supports -p, etc.

if test $# -ne 2; then
  echo "Usage: $0 CAPSULE.txt OUTPUTDIR" >&2
  exit 1
fi

if test ! -s "$1"; then
  echo "$0: capsule file does not exist or is empty: $1" >&2
  exit 1
fi
capsule=$1

if test ! -d "$2"; then
  echo "$0: output not a directory: $2" >&2
  exit 1
fi
outdir=$2

# Extract the volume, issue, and sequence number from the \issue line in
# the capsule file. We don't use anything else.
# \issue{41}{3}{129}{2020}{}{}
set - `grep '^\\\\issue' "$capsule" | sed -n 's/[{}]/ /gp'`
#
volno=$2
issno=$3
seqno=$4

# Our convention is that the issue sources are in ~tubprod/VV-N/*,
# while this script is in ~tubprod/svn/capsules (an svn checkout).
# Use a relative path instead of hardwiring ~tubprod, but assume
# that layout.
# 
mydir=`cd \`dirname "$0"\` && pwd`  # .../svn/capsules
issdir=`cd "$mydir/../../$volno-$issno" && pwd`

if test ! -d "$issdir"; then
  echo "$0: could not find issue directory: $issdir" >&2
  echo "$0: (from volno=$volno, issno=$issno, seqno=$seqno)" >&2
  exit 1
fi

bbl_count=`ls -1 $issdir/*/tb*.bbl 2>/dev/null | wc -l`
if test $bbl_count -eq 0; then
  echo "$0: no .bbl files found under: $issdir" >&2
  exit 1
fi
#
abs_count=`ls -1 $issdir/*/abs.tex 2>/dev/null | wc -l`
if test $abs_count -eq 0; then
  echo "$0: no abs.tex files found under: $issdir" >&2
  exit 1
fi

# We intentionally do not erase existing files or move them aside;
# let another level (the cr-do-issue script) do that. Which it does.
# 
if cp -pf $issdir/*/tb*.bbl $outdir/; then :; else
  echo "$0: copy of bbl files failed, goodbye." >&2
  exit 1
fi

# For the abstracts, we want to add the tbNNNident prefix. We don't use
# it with the source abs.tex files for the sake of completion (and simplicity).
# 
for a in $issdir/*/abs.tex; do
  ident=`basename \`dirname "$a"\``
  dest=$outdir/tb${seqno}${ident}.abs
  cp -pf "$a" "$dest" || exit 1
done  

echo "$0: $bbl_count bbl(s) and $abs_count abstract(s) copied: $outdir"
exit 0
